name: solana-toolchain

runs:
  using: "composite"
  steps:
    - id: get-version
      shell: bash
      run: |
        SOLANA_VERSION=$(cat solana-toolchain)
        echo "solana-version=$SOLANA_VERSION" >> $GITHUB_OUTPUT
    - uses: metaplex-foundation/actions/install-solana@v1
      with:
        cache: true
        version: ${{ steps.get-version.outputs.solana-version }}

